### ISSUE TITLE
Integration: Aave

### ISSUE THREAD

**Issue by drakedanner** [nftchance/plug-router#74]
Spec Sheet (Aave V2): https://docs.google.com/document/d/19J3y0BL8CAnx2eMrHy7N8HZ_H2jaXyXt8YCRC9Za1yg/edit?usp=sharing

Spec Sheet (Aave V3): 
https://docs.google.com/document/d/1PoWPQz2M-AG2YvLIdtsoWA3-cCgOTde44-EPN6kiyck/edit

**Comment by nftchance** [comment]
Implemented by 0b7fac83696f7abfc68e83e90c0e78e51c0aac98 in https://github.com/nftchance/solver
